# Generated by Django 4.2.7 on 2026-06-11 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='站点名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='站点编码')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='地址')),
                ('contact', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '服务站点',
                'verbose_name_plural': '服务站点',
                'db_table': 'service_site',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='服务类型名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='服务类型编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '服务类型',
                'verbose_name_plural': '服务类型',
                'db_table': 'service_type',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=50, unique=True, verbose_name='事项编号')),
                ('title', models.CharField(max_length=200, verbose_name='事项标题')),
                ('applicant_name', models.CharField(max_length=100, verbose_name='申请人姓名')),
                ('applicant_phone', models.CharField(max_length=20, verbose_name='申请人电话')),
                ('applicant_id_card', models.CharField(blank=True, max_length=18, verbose_name='申请人身份证')),
                ('description', models.TextField(verbose_name='事项描述')),
                ('status', models.CharField(choices=[('PENDING_ACCEPT', '待受理'), ('PROCESSING', '处理中'), ('PENDING_REVIEW', '待复核'), ('CLOSED', '已关闭'), ('CANCELLED', '已取消')], default='PENDING_ACCEPT', max_length=20, verbose_name='状态')),
                ('handler_note', models.TextField(blank=True, verbose_name='处理说明')),
                ('review_note', models.TextField(blank=True, verbose_name='复核说明')),
                ('appointment_time', models.DateTimeField(blank=True, null=True, verbose_name='预约时间')),
                ('accept_time', models.DateTimeField(blank=True, null=True, verbose_name='受理时间')),
                ('process_start_time', models.DateTimeField(blank=True, null=True, verbose_name='处理开始时间')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('close_time', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('cancel_time', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='取消原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_items', to=settings.AUTH_USER_MODEL, verbose_name='当前负责人')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_items', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_items', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.servicetype', verbose_name='服务类型')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.servicesite', verbose_name='服务站点')),
            ],
            options={
                'verbose_name': '服务事项',
                'verbose_name_plural': '服务事项',
                'db_table': 'service_item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('CREATE', '创建事项'), ('STATUS_CHANGE', '状态变更'), ('ASSIGNEE_CHANGE', '负责人变更'), ('HANDLER_NOTE_CHANGE', '处理说明修改'), ('APPOINTMENT_CHANGE', '预约时间调整'), ('CANCEL', '取消事项'), ('UNDO', '撤销操作'), ('REDO', '重做操作')], max_length=30, verbose_name='操作类型')),
                ('operation_note', models.TextField(blank=True, verbose_name='操作说明')),
                ('before_snapshot', models.JSONField(blank=True, default=dict, verbose_name='变更前快照')),
                ('after_snapshot', models.JSONField(blank=True, default=dict, verbose_name='变更后快照')),
                ('is_undone', models.BooleanField(default=False, verbose_name='是否已撤销')),
                ('undone_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('redo_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redo_logs', to='service.auditlog', verbose_name='重做对应的原操作')),
                ('service_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='service.serviceitem', verbose_name='服务事项')),
                ('undone_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='undone_logs', to=settings.AUTH_USER_MODEL, verbose_name='撤销人')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
